apiVersion: v1
kind: Service
metadata:
  labels:
    app: voting-ui
  name: voting-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 9090
  selector:
    app: voting-ui
